init:
	gcc -o init init.c
	./init
	rm init

seq:
	gcc -o sequential sequential.c
	./sequential
	rm sequential

pthra:
	gcc -pthread -o pthreada pthreada.c
	./pthreada
	rm pthreada

pthrb:
	gcc -pthread -o pthreadb pthreadb.c
	./pthreadb
	rm pthreadb

pthrc:
	gcc -pthread -o pthreadc pthreadc.c
	./pthreadc
	rm pthreadc

ompa:
	gcc -fopenmp -o openmpa openmpa.c
	./openmpa
	rm openmpa

ompb:
	gcc -fopenmp -o openmpb openmpb.c
	./openmpb
	rm openmpb

ompc:
	gcc -fopenmp -o openmpc openmpc.c
	./openmpc
	rm openmpc

cl_seq:
	rm sequential

cl_pthra:
	rm pthreada

cl_pthrb:
	rm pthreadb

cl_pthrc:
	rm pthreadc

cl_ompa:
	rm openmpa

cl_ompb:
	rm openmpb

cl_ompc:
	rm openmpc

clean:
	rm z_m_1_n_1_l_10
	rm z_m_1_n_1_l_100
	rm z_m_1_n_1_l_1000
	rm z_m_1_n_100_l_10
	rm z_m_1_n_100_l_100
	rm z_m_1_n_100_l_1000
	rm z_m_1_n_1000_l_10
	rm z_m_1_n_1000_l_100
	rm z_m_1_n_1000_l_1000
	rm z_m_1_n_10000_l_10
	rm z_m_1_n_10000_l_100
	rm z_m_1_n_10000_l_1000
	rm z_m_100_n_1_l_10
	rm z_m_100_n_1_l_100
	rm z_m_100_n_1_l_1000
	rm z_m_100_n_100_l_10
	rm z_m_100_n_100_l_100
	rm z_m_100_n_100_l_1000
	rm z_m_100_n_1000_l_10
	rm z_m_100_n_1000_l_100
	rm z_m_100_n_1000_l_1000
	rm z_m_100_n_10000_l_10
	rm z_m_100_n_10000_l_100
	rm z_m_100_n_10000_l_1000
	rm z_m_1000_n_1_l_10
	rm z_m_1000_n_1_l_100
	rm z_m_1000_n_1_l_1000
	rm z_m_1000_n_100_l_10
	rm z_m_1000_n_100_l_100
	rm z_m_1000_n_100_l_1000
	rm z_m_1000_n_1000_l_10
	rm z_m_1000_n_1000_l_100
	rm z_m_1000_n_1000_l_1000
	rm z_m_1000_n_10000_l_10
	rm z_m_1000_n_10000_l_100
	rm z_m_1000_n_10000_l_1000
	rm z_m_10000_n_1_l_10
	rm z_m_10000_n_1_l_100
	rm z_m_10000_n_1_l_1000
	rm z_m_10000_n_100_l_10
	rm z_m_10000_n_100_l_100
	rm z_m_10000_n_100_l_1000
	rm z_m_10000_n_1000_l_10
	rm z_m_10000_n_1000_l_100
	rm z_m_10000_n_1000_l_1000
	rm z_m_10000_n_10000_l_10
	rm z_m_10000_n_10000_l_100
	rm z_m_10000_n_10000_l_1000

	## Done ##